### ISSUE TITLE
Select a category from "Custom Category section"

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Zifer-Child#10]
Scoate textul "Select a category from "Custom Category section", categoria by default sa fie, categoria cu id 1.

**Comment by nikkyandrei** [comment]
categoria cu id=1 nu e Uncategorized ?

**Comment by nikkyandrei** [comment]
nu am scos , daca vrei alt text sa imi zici

**Comment by robi09** [comment]
Ba da, categoria uncategorized este cu id 1, dar este mai ok sa pui id-ul decat numele.

**Comment by nikkyandrei** [comment]
nu trebuie sa pui numele , ai un select in customizer , si iti alegi categoria , in felul asta nu tebuie sa stii care ce id are
