### ISSUE TITLE
Link documentatie

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Zifer-Child#11]
Adauga acest link pentru documentatie in customizr:
https://themeisle.com/zifer-child-theme-documentation

**Comment by ineagu** [comment]
@robi09 nu merge aceeasi documentatie ca la zerif lite ?

**Comment by robi09** [comment]
Cred ca da, nu m-am uitat sincer. O sa verific.

**Comment by robi09** [comment]
Partial merge, sunt cateva lucruri noi in tema asta. @ineagu  sa imi spui cum procedam.

**Comment by ineagu** [comment]
pai am putea adauga ce e nevoie in acceasi documentatie ca o sectiune noua

**Comment by robi09** [comment]
@ineagu ok, ne ocupam noi de acest aspect?

**Comment by ineagu** [comment]
@robi09 da

**Comment by robi09** [comment]
@nikkyandrei  uite link-ul https://themeisle.com/documentation-zerif-lite/
