### ISSUE TITLE
Default logo

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Zifer-Child#12]
Sa verifici ca logo-ul sa nu fie pus acolo by default, sa fie optiune in customizer pentru adaugare logo, dar by default sa fie nume + descriere blog.

**Comment by nikkyandrei** [comment]
Este obtiune in customizer
 Pe 17.01.2015 12:44, "Hapiuc Robert" <notifications@github.com> a scris:

**Comment by ineagu** [comment]
pt logo folosim setarile parinte nu ? ce treaba avem cu asta in child ?

**Comment by nikkyandrei** [comment]
pai le-am lasta alea din parinte ..
