### ISSUE TITLE
Efect aiurea

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Zifer-Child#14]
@nikkyandrei @robi09 cand sunt aici ; http://demo.themeisle.com/zifer-child/?p=66 si dau click pe un post se mareste->micsoreaza scrisul, cred ca e un bug ceva.

**Comment by ineagu** [comment]
am pb asta si pe home, cred ca e din cauza ca incarcam js la ready si nu la load, va puteti uita ?

**Comment by robi09** [comment]
@nikkyandrei  sa te ocupi te rog te issues aici maine, este urgent.

**Comment by robi09** [comment]
@nikkyandrei  problema aici este font-size: 62.5% aplicat pe html, el este aplicat acolo deoarece la inceput se vroia a se folosii rem dar s'a folosit px, adauga si in child un font-size default pe html.

**Comment by nikkyandrei** [comment]
@robi09  am scos efectul

**Comment by ineagu** [comment]
eu nu vad asta reparat pe demo @robi09

**Comment by robi09** [comment]
Inca nu s'a facut update pe demo.
