### ISSUE TITLE
scos featured image

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Zifer-Child#15]
tinand cont ca peste tot in tema folosim featured image patrat, nu prea avem cum sa il folosim in felul asta : http://demo.themeisle.com/zifer-child/?p=66 , ori il scoatem ori il aranjam altfel @robi09 @nikkyandrei

**Comment by robi09** [comment]
@nikkyandrei pe single fa un div de 600x400 si pune feat img ca si background apoi aplica background-size cover.

**Comment by nikkyandrei** [comment]
@robi09  vezi daca iti place
