### ISSUE TITLE
Top menu links demo

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Zifer-Child#16]
@robi09 putem pune link-urile cu #xxx in meniul de sus de pe demo : http://demo.themeisle.com/zifer-child/ ? ca sa stie oamenii cum sa puna ?

De asemenea link-ul de home ma duce aici, ceea e total gresit : http://9pixels.co/team/al/wp/

**Comment by nikkyandrei** [comment]
am vazut ca sunt facute
