### ISSUE TITLE
wrong branch names

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Zifer-Child#18]
@robi09 ar trebui sa avem doar development/production ambele cu litere mici, este f important.

**Comment by robi09** [comment]
@ineagu se pot schimba direct din admin?

**Comment by ineagu** [comment]
cred ca da

**Comment by ineagu** [comment]
@robi09 cand rezolvam si noi cu astea ?

**Comment by robciucioan** [comment]
@robi09, nu pot schimba numele branch-ului din "Development" în "development".

**Comment by ineagu** [comment]
ok, macar rezolva cele raportate de wp.org :D

**Comment by robi09** [comment]
@robciuc o sa ma creez eu alte brenchrui si fac merge acolo, dar nu pot acum ca am o groaza pe cap. In seara asta o sa fac sau cel tarziu maine dim.






From: Ionut Neagu
Sent: ‎Friday‎, ‎February‎ ‎13‎, ‎2015 ‎6‎:‎54‎ ‎PM
To: Codeinwp/Zifer-Child
Cc: Hapiuc Robert




ok, macar rezolva cele raportate de wp.org :D
