### ISSUE TITLE
footer text

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Zifer-Child#19]
In footer "Zerif Lite" trebuie sa preia automat numele temei.

**Comment by nikkyandrei** [comment]
preia automat numele temei dar si linkul din stile de la theme uri .
sa imi zici ce link sa pun in style

**Comment by robi09** [comment]
Uite link-ul: https://themeisle.com/themes/zifer-child/

**Comment by nikkyandrei** [comment]
done
