### ISSUE TITLE
nu exista descriere

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Zifer-Child#25]
Adaugi o descriere mai de doamne ajuta nu e atat de greu, mai aranjati ce corespunde si ce nu de ex : 

"The Virtue theme is extremely versatile with tons of options, easy to customize and loaded with great features. The clean modern design is built with html5 and css3 and uses the powerful responsive framework from Bootstrap to be a fully responsive and mobile friendly. It's fully ecommerce (Woocommerce) ready with all the tools you need to design an awesome online store. The versatile design is perfect for any kind of business, online store, portfolio or personal site. We built Virtue with a powerful options panel where you can set things like your home layout, sliders, custom fonts, and completely customize your look without writing any CSS. You are going to love how easy this theme is to work with. Virtue was built and designed by Kadence Themes."

**Comment by robi09** [comment]
"The Zifer theme is a user optimized Photography WordPress Theme built with latest technologies, easy to customize. use it to create an awesome photography portoflio"
