### ISSUE TITLE
Eroare logo

### ISSUE THREAD

**Issue by ioanrobciuc** [Codeinwp/Zifer-Child#30]
Tema child vine făra folder-ul "images". Așa trebuie să fie?
![image](https://cloud.githubusercontent.com/assets/8695094/6191349/6139bbae-b3b1-11e4-8aab-ed7d36e1573e.png)

**Comment by ineagu** [comment]
btw la prima instalare tema pare ca arata f rau, ar trebui niste chestii default puse..

**Comment by robciucioan** [comment]
@ineagu, o să creez issue pentru text default în customizer.

**Comment by robciucioan** [comment]
Am rezolvat problema în commit-ul #28.
