### ISSUE TITLE
Theme URI

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Zifer-Child#7]
La theme URI trece datele themeisle.com, pentru ca task-ul a fost postat in proiectul Themeisle pe TM.  La fel si la restul datelor.

**Comment by ineagu** [comment]
@robi09 nu o sa avem theme uri pt tema asta, o sa fie doar pe wp.org

**Comment by ineagu** [comment]
sau nici nu stiu ce sa zic, o pot vedea pe demo ? pare ca e destul de diferita :)

**Comment by nikkyandrei** [comment]
done

**Comment by robi09** [comment]
@ineagu  am inceput deja procedura pentru demo, nu am stiut ca nu o vrei. Eu zic sa o punem, arata foarte bine tema.

**Comment by robi09** [comment]
Schimba si restul datelor 

/*
 Theme Name:	 Zifer Child
 Theme URI:		 https://themeisle.com
 Description:	 Zifer Child - Zerif child theme
 Author:		 9pixels
 Author URI:	 http://9pixels.co
 Template:		 zerif-litess
 Version:		 1.0.0
 Tags: black, gray, red, white, one-column, two-columns, right-sidebar,fixed-layout,light,front-page-post-form,full-width-template,rtl-language-support,sticky-post,theme-options,responsive-layout, custom-background, custom-menu, editor-style, featured-images, threaded-comments, translation-ready
 Text Domain:	zifer-child
 Domain Pat

Nu trebuie sa apara 9px asu pthg in proiectele cwp/ti. :)
